"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from bannerify.types import BaseModel
from bannerify.utils import FieldMetadata, QueryParamMetadata
import pydantic
from typing import TypedDict
from typing_extensions import Annotated


class GetV1InfoRequestTypedDict(TypedDict):
    api_key: str
    

class GetV1InfoRequest(BaseModel):
    api_key: Annotated[str, pydantic.Field(alias="apiKey"), FieldMetadata(query=QueryParamMetadata(style="form", explode=True))]
    

class GetV1InfoResponseBodyTypedDict(TypedDict):
    r"""Project info"""
    
    id: str
    name: str
    created_at: str
    

class GetV1InfoResponseBody(BaseModel):
    r"""Project info"""
    
    id: str
    name: str
    created_at: Annotated[str, pydantic.Field(alias="createdAt")]
    
