workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    bannerify-OAS:
        inputs:
            - location: https://api.bannerify.co/openapi
        registry:
            location: registry.speakeasyapi.dev/bannerify/bannerify/bannerify-oas
targets:
    bannerify:
        target: python
        source: bannerify-OAS
        codeSamples:
            output: codeSamples.yaml
            registry:
                location: registry.speakeasyapi.dev/bannerify/bannerify/code-samples-python-bannerify
